sudo: required

language: python

services:
  - docker

script:
  - docker build -t hackerbomzzzhack/myapp:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hackerbomzzzhack/myapp
