sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t hackerbomzzzhack/myapp:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hackerbomzzzhack/myapp
