language: python

services:
  - docker

before_install:
  - docker build -t flask-sample-one:latest .
  - docker run -d -p 5000:5000 simple-flask-app
  - docker ps

script:
  - docker run -d -p 5000:5000 simple-flask-app
  - docker ps

